---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/rootfs

inputs:
- name: pcf-pipelines-utils

run:
  path: pcf-pipelines-utils/tasks/utils/configure-pks/task.sh

params:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  OPSMAN_CLIENT_ID:
  OPSMAN_CLIENT_SECRET:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  TILE_PROPERTIES:
  TILE_NETWORK:
  TILE_RESOURCES:
  TILE_PRODUCT_NAME:
  CERT_DOMAIN:
