resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: pcf-pipelines-tarball
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: pcf-automation
    product_version: {{pcf-pipelines-release-or-tag}}

- name: pcf-pipelines-maestro
  type: git
  source:
    uri: {{maestro_project_url}}
    private_key: {{git_maestro_private_key}}

- name: stemcells
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: stemcells
    product_version: {{stemcell_version}}

jobs:
- name: Get-and-Upload-Stemcell
  plan:
  - get: pcf-pipelines-maestro
  - get: stemcells
    params:
      globs: ["*((iaas_type))*"]
  - task: upload-stemcell
    file: pcf-pipelines-maestro/tasks/utils/upload-stemcell-version/task.yml
    input_mapping:
      custom-pipeline-tasks: pcf-pipelines-maestro
    params:
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_URI: {{opsman_domain_or_ip_address}}

- name: Apply-Change
  plan:
  - do:
    - get: pcf-pipelines-tarball
    - task: unpack-tarball
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: pcfnorm/rootfs
        run:
          path: bash
          args:
          - -c
          - tar -xvf pcf-pipelines-tarball/*.tgz
        inputs:
        - name: pcf-pipelines-tarball
        outputs:
        - name: pcf-pipelines
  - get: pcf-pipelines-maestro
    passed:
    - Get-and-Upload-Stemcell

  - task: wait-opsman-clear-running-tasks
    file: pcf-pipelines-maestro/tasks/utils/wait-opsman-clear-running-tasks/task.yml
    params:
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}

  - task: apply-changes
    file: pcf-pipelines/tasks/apply-changes/task.yml
    params:
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
