groups: []
resources:
- name: pcf-pipelines-maestro
  type: git
  source:
    uri: {{maestro_project_url}}
- name: pcf-pipelines-tarball
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: pcf-automation
    product_version: {{pcf-pipelines-release-or-tag}}
resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final
jobs:
- name: orchestrate-pipelines
  plan:
  - get: pcf-pipelines-maestro
    trigger: true
  - do:
    - get: pcf-pipelines-tarball
    - task: unpack-tarball
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: pcfnorm/rootfs
        run:
          path: bash
          args:
          - -c
          - tar -xvf pcf-pipelines-tarball/*.tgz
        inputs:
        - name: pcf-pipelines-tarball
        outputs:
        - name: pcf-pipelines
  - task: conduct-updates-to-pipelines
    file: pcf-pipelines-maestro/tasks/maestro/task.yml
    params:
      MAIN_CONCOURSE_PASSWORD: {{concourse_main_pass}}
      MAIN_CONCOURSE_SKIP_SSL: {{concourse_skip_ssl_verification}}
      MAIN_CONCOURSE_URL: {{concourse_url}}
      MAIN_CONCOURSE_USERNAME: {{concourse_main_userid}}
